package com.example.compose
import androidx.compose.ui.graphics.Color

val primaryLightHighContrast = Color(0xFF3B0057)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF6C009B)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF3B0057)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF651E8A)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF49002D)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF840055)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF7FC)
val onBackgroundLightHighContrast = Color(0xFF211924)
val surfaceLightHighContrast = Color(0xFFFFF7FC)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFF0DCF3)
val onSurfaceVariantLightHighContrast = Color(0xFF2B2030)
val outlineLightHighContrast = Color(0xFF4B3E50)
val outlineVariantLightHighContrast = Color(0xFF4B3E50)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF362D39)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFBE5FF)
val surfaceDimLightHighContrast = Color(0xFFE4D5E6)
val surfaceBrightLightHighContrast = Color(0xFFFFF7FC)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFFEEFFF)
val surfaceContainerLightHighContrast = Color(0xFFF9E9FA)
val surfaceContainerHighLightHighContrast = Color(0xFFF3E3F4)
val surfaceContainerHighestLightHighContrast = Color(0xFFEDDEEE)

val primaryDarkHighContrast = Color(0xFFFFF9FB)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFEAB9FF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFF9FB)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFEAB9FF)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFF9F9)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFB6D4)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF18111C)
val onBackgroundDarkHighContrast = Color(0xFFEDDEEE)
val surfaceDarkHighContrast = Color(0xFF18111C)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4F4254)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFF9FB)
val outlineDarkHighContrast = Color(0xFFD7C5DB)
val outlineVariantDarkHighContrast = Color(0xFFD7C5DB)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFEDDEEE)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF470067)
val surfaceDimDarkHighContrast = Color(0xFF18111C)
val surfaceBrightDarkHighContrast = Color(0xFF3F3642)
val surfaceContainerLowestDarkHighContrast = Color(0xFF130B16)
val surfaceContainerLowDarkHighContrast = Color(0xFF211924)
val surfaceContainerDarkHighContrast = Color(0xFF251D28)
val surfaceContainerHighDarkHighContrast = Color(0xFF302733)
val surfaceContainerHighestDarkHighContrast = Color(0xFF3B323E)







